spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test-db?createDatabaseIfNotExist=true
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
